In [48]:
import pandas as pd
import numpy as np

In [49]:
# it is a whole covid dataset by county daily
covid_df = pd.read_csv('./dataset/US_counties_COVID19_health_weather_data.csv')

In [50]:
covid_df

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,Illinois,17031,1,0.0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,Wyoming,56037,2077,10.0,no,no,41.659538,-108.879567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790327,2020-12-04,Teton,Wyoming,56039,1724,2.0,no,no,43.934776,-110.589759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790328,2020-12-04,Uinta,Wyoming,56041,1175,5.0,no,no,41.287648,-110.547639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790329,2020-12-04,Washakie,Wyoming,56043,517,8.0,no,no,43.904970,-107.682819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790330,2020-12-04,Weston,Wyoming,56045,419,2.0,no,no,43.840417,-104.567663,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
state_abbr = pd.read_csv('./dataset/state_abbr.csv')
state_abbr_dict = state_abbr.set_index('State').to_dict()['Abbreviation']
covid_df['state'] = covid_df['state'].map(state_abbr_dict)

In [52]:
covid_df

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,WA,53061,1,0.0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,WA,53061,1,0.0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,WA,53061,1,0.0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,IL,17031,1,0.0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,WA,53061,1,0.0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,WY,56037,2077,10.0,no,no,41.659538,-108.879567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790327,2020-12-04,Teton,WY,56039,1724,2.0,no,no,43.934776,-110.589759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790328,2020-12-04,Uinta,WY,56041,1175,5.0,no,no,41.287648,-110.547639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790329,2020-12-04,Washakie,WY,56043,517,8.0,no,no,43.904970,-107.682819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790330,2020-12-04,Weston,WY,56045,419,2.0,no,no,43.840417,-104.567663,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The dataframe is too large, we only keep the the columns we need ['date', 'county', 'state', 'cases', 'deaths', 'stay_at_home_announced', 'stay_at_home_effective', 'total_population',
             'population_density_per_sqmi', 'date_stay_at_home_announced', 'date_stay_at_home_effective','fog','rain','snow','thunder',
            'visibility', 'max_wind_speed', 'percent_unemployed_CHR', 'percent_below_poverty', 'lat', 'lon']
The fips is to identify the county. And we have kept some weather data to exclude the possibilty that weather may affect the airlines

In [53]:
kept_col = ['date', 'county', 'state', 'fips', 'cases', 'deaths', 'stay_at_home_announced', 'stay_at_home_effective', 'total_population',
             'population_density_per_sqmi', 'date_stay_at_home_announced', 'date_stay_at_home_effective','fog','rain','snow','thunder',
            'visibility', 'max_wind_speed', 'percent_unemployed_CHR', 'percent_below_poverty', 'lat', 'lon']
covid_clean_df = covid_df[kept_col]
covid_clean_df

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,total_population,population_density_per_sqmi,...,fog,rain,snow,thunder,visibility,max_wind_speed,percent_unemployed_CHR,percent_below_poverty,lat,lon
0,2020-01-21,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.9,19.0,3.758915,9.3,48.047489,-121.697307
1,2020-01-22,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.6,21.0,3.758915,9.3,48.047489,-121.697307
2,2020-01-23,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,10.0,20.0,3.758915,9.3,48.047489,-121.697307
3,2020-01-24,Cook,IL,17031,1,0.0,no,no,5227575.0,5531.878539,...,1.0,1.0,1.0,0.0,2.5,9.9,4.036321,16.7,41.840039,-87.816716
4,2020-01-24,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.6,22.0,3.758915,9.3,48.047489,-121.697307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,WY,56037,2077,10.0,no,no,44812.0,4.297803,...,0.0,0.0,0.0,0.0,10.0,7.0,4.236407,11.0,41.659538,-108.879567
790327,2020-12-04,Teton,WY,56039,1724,2.0,no,no,22623.0,5.661502,...,0.0,0.0,0.0,0.0,NaN,NaN,3.024772,7.3,43.934776,-110.589759
790328,2020-12-04,Uinta,WY,56041,1175,5.0,no,no,20893.0,10.035892,...,0.0,0.0,0.0,0.0,10.0,8.9,4.366812,16.8,41.287648,-110.547639
790329,2020-12-04,Washakie,WY,56043,517,8.0,no,no,8351.0,3.730539,...,0.0,0.0,0.0,0.0,10.0,4.1,4.238541,14.7,43.904970,-107.682819
790330,2020-12-04,Weston,WY,56045,419,2.0,no,no,7175.0,2.991964,...,0.0,0.0,0.0,0.0,NaN,NaN,3.511123,14.7,43.840417,-104.567663

In [54]:
# convert the date into standard format
covid_clean_df['date'] = pd.to_datetime(covid_clean_df['date'])
covid_clean_df

C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\1663476244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_clean_df['date'] = pd.to_datetime(covid_clean_df['date'])

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,total_population,population_density_per_sqmi,...,fog,rain,snow,thunder,visibility,max_wind_speed,percent_unemployed_CHR,percent_below_poverty,lat,lon
0,2020-01-21,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.9,19.0,3.758915,9.3,48.047489,-121.697307
1,2020-01-22,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.6,21.0,3.758915,9.3,48.047489,-121.697307
2,2020-01-23,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,10.0,20.0,3.758915,9.3,48.047489,-121.697307
3,2020-01-24,Cook,IL,17031,1,0.0,no,no,5227575.0,5531.878539,...,1.0,1.0,1.0,0.0,2.5,9.9,4.036321,16.7,41.840039,-87.816716
4,2020-01-24,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,1.0,0.0,0.0,9.6,22.0,3.758915,9.3,48.047489,-121.697307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,WY,56037,2077,10.0,no,no,44812.0,4.297803,...,0.0,0.0,0.0,0.0,10.0,7.0,4.236407,11.0,41.659538,-108.879567
790327,2020-12-04,Teton,WY,56039,1724,2.0,no,no,22623.0,5.661502,...,0.0,0.0,0.0,0.0,NaN,NaN,3.024772,7.3,43.934776,-110.589759
790328,2020-12-04,Uinta,WY,56041,1175,5.0,no,no,20893.0,10.035892,...,0.0,0.0,0.0,0.0,10.0,8.9,4.366812,16.8,41.287648,-110.547639
790329,2020-12-04,Washakie,WY,56043,517,8.0,no,no,8351.0,3.730539,...,0.0,0.0,0.0,0.0,10.0,4.1,4.238541,14.7,43.904970,-107.682819
790330,2020-12-04,Weston,WY,56045,419,2.0,no,no,7175.0,2.991964,...,0.0,0.0,0.0,0.0,NaN,NaN,3.511123,14.7,43.840417,-104.567663

In [55]:
# have new columns YEAR and week
covid_clean_df['WEEK'] = covid_clean_df['date'].dt.weekofyear
covid_clean_df['YEAR'] = covid_clean_df['date'].dt.year

C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\1467893560.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  covid_clean_df['WEEK'] = covid_clean_df['date'].dt.weekofyear
C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\1467893560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_clean_df['WEEK'] = covid_clean_df['date'].dt.weekofyear
C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\1467893560.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_clean_df['YEAR'] = covid_clean_df['date'].dt.year

In [56]:
covid_clean_df

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,total_population,population_density_per_sqmi,...,snow,thunder,visibility,max_wind_speed,percent_unemployed_CHR,percent_below_poverty,lat,lon,WEEK,YEAR
0,2020-01-21,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,0.0,9.9,19.0,3.758915,9.3,48.047489,-121.697307,4,2020
1,2020-01-22,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,0.0,9.6,21.0,3.758915,9.3,48.047489,-121.697307,4,2020
2,2020-01-23,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,0.0,10.0,20.0,3.758915,9.3,48.047489,-121.697307,4,2020
3,2020-01-24,Cook,IL,17031,1,0.0,no,no,5227575.0,5531.878539,...,1.0,0.0,2.5,9.9,4.036321,16.7,41.840039,-87.816716,4,2020
4,2020-01-24,Snohomish,WA,53061,1,0.0,no,no,758649.0,363.586159,...,0.0,0.0,9.6,22.0,3.758915,9.3,48.047489,-121.697307,4,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,WY,56037,2077,10.0,no,no,44812.0,4.297803,...,0.0,0.0,10.0,7.0,4.236407,11.0,41.659538,-108.879567,49,2020
790327,2020-12-04,Teton,WY,56039,1724,2.0,no,no,22623.0,5.661502,...,0.0,0.0,NaN,NaN,3.024772,7.3,43.934776,-110.589759,49,2020
790328,2020-12-04,Uinta,WY,56041,1175,5.0,no,no,20893.0,10.035892,...,0.0,0.0,10.0,8.9,4.366812,16.8,41.287648,-110.547639,49,2020
790329,2020-12-04,Washakie,WY,56043,517,8.0,no,no,8351.0,3.730539,...,0.0,0.0,10.0,4.1,4.238541,14.7,43.904970,-107.682819,49,2020
790330,2020-12-04,Weston,WY,56045,419,2.0,no,no,7175.0,2.991964,...,0.0,0.0,NaN,NaN,3.511123,14.7,43.840417,-104.567663,49,2020

In [57]:
covid_clean_df.to_csv('./dataset/covid_clean_df_date', index=False)

We group by each county weekly using its identical fips.
For each columns after group, we use specific aggregate method

In [58]:
group_covid_df = covid_clean_df.groupby(['fips', 'YEAR', 'WEEK'])

kept_col = ['date', 'county', 'state', 'fips', 'cases', 'deaths', 'stay_at_home_announced', 'stay_at_home_effective', 'total_population',
             'population_density_per_sqmi', 'date_stay_at_home_announced', 'date_stay_at_home_effective','fog','rain','snow','thunder',
            'visibility', 'max_wind_speed', 'percent_unemployed_CHR', 'percent_below_poverty', 'lat', 'lon']

In [59]:
group_covid_agg_df = group_covid_df.agg({
    'cases': 'last',    # we choose the case number in last day to represent the total cases a week
    'deaths': 'last',   # same as case
    'county' : 'first', 
    'state'  : 'first', 
    'stay_at_home_announced' :  lambda x: 'yes' if (x == 'yes').sum() >= 4 else 'no',
    'stay_at_home_effective' :  lambda x: 'yes' if (x == 'yes').sum() >= 4 else 'no',
    'total_population': 'first',
    'population_density_per_sqmi': 'first',
    'date_stay_at_home_announced': 'first', 
    'date_stay_at_home_effective': 'first', # the day that required to stay at home
    'percent_unemployed_CHR': 'mean',
    'percent_below_poverty': 'mean',
    'fog': 'sum',
    'rain': 'sum',
    'snow': 'sum',  
    'thunder': 'sum',               # we sum up the day with severe weather 
    'visibility': 'mean',
    'max_wind_speed': 'mean',       # we use mean value for the weather
    'lat' : 'first',                
    'lon' : 'first'
})
# group_covid_agg_df = group_covid_df.agg({'stay_at_home_effective': lambda x: 'yes' if (x == 'yes').sum() >= 4 else 'no'})

In [60]:
group_covid_agg_df

                 cases  deaths     county state stay_at_home_announced  \
fips  YEAR WEEK
01001 2020 13        6     0.0    Autauga    AL                     no
           14       12     0.0    Autauga    AL                     no
           15       19     1.0    Autauga    AL                    yes
           16       27     2.0    Autauga    AL                    yes
           17       37     2.0    Autauga    AL                    yes
...                ...     ...        ...   ...                    ...
VI    2020 45      803    15.0  St. Croix  None                     no
           46      812    15.0  St. Croix  None                     no
           47      849    15.0  St. Croix  None                     no
           48      869    15.0  St. Croix  None                     no
           49      898    15.0  St. Croix  None                     no

                stay_at_home_effective  total_population  \
fips  YEAR WEEK
01001 2020 13                       no           55049.0
           14                       no           55049.0
           15                      yes           55049.0
           16                      yes           55049.0
           17                      yes           55049.0
...                                ...               ...
VI    2020 45                       no               NaN
           46                       no               NaN
           47                       no               NaN
           48                       no               NaN
           49                       no               NaN

                 population_density_per_sqmi date_stay_at_home_announced  \
fips  YEAR WEEK
01001 2020 13                      92.605533                  2020-04-03
           14                      92.605533                  2020-04-03
           15                      92.605533                  2020-04-03
           16                      92.605533                  2020-04-03
           17                      92.605533                  2020-04-03
...                                      ...                         ...
VI    2020 45                            NaN                        None
           46                            NaN                        None
           47                            NaN                        None
           48                            NaN                        None
           49                            NaN                        None

                date_stay_at_home_effective  percent_unemployed_CHR  \
fips  YEAR WEEK
01001 2020 13                    2020-04-04                3.629079
           14                    2020-04-04                3.629079
           15                    2020-04-04                3.629079
           16                    2020-04-04                3.629079
           17                    2020-04-04                3.629079
...                                     ...                     ...
VI    2020 45                          None                     NaN
           46                          None                     NaN
           47                          None                     NaN
           48                          None                     NaN
           49                          None                     NaN

                 percent_below_poverty  fog  rain  snow  thunder  visibility  \
fips  YEAR WEEK
01001 2020 13                     12.3  0.0   1.0   0.0      0.0    9.633333
           14                     12.3  0.0   2.0   0.0      1.0    9.971429
           15                     12.3  2.0   5.0   0.0      2.0    9.128571
           16                     12.3  0.0   3.0   0.0      2.0    9.785714
           17                     12.3  2.0   3.0   0.0      2.0    9.200000
...                                ...  ...   ...   ...      ...         ...
VI    2020 45                      NaN  0.0   0.0   0.0      0.0         NaN
           46                      NaN  0.0   0.0   0.0      0.0         NaN
           47                      NaN  0.0   0.0   0.0      0.0         NaN
           48                      NaN  0.0   0.0   0.0      0.0         NaN
           49                      NaN  0.0   0.0   0.0      0.0         NaN

                 max_wind_speed        lat        lon
fips  YEAR WEEK
01001 2020 13         10.333333  32.534928 -86.642748
           14          8.328571  32.534928 -86.642748
           15         11.842857  32.534928 -86.642748
           16         13.414286  32.534928 -86.642748
           17         12.128571  32.534928 -86.642748
...                         ...        ...        ...
VI    2020 45               NaN        NaN        NaN
           46               NaN        NaN        NaN
           47               NaN        NaN        NaN
           48               NaN        NaN        NaN
           49               NaN        NaN        NaN

[112693 rows x 20 columns]

In [61]:
# we can find weekly increasing cases by have the diff of previous week
group_covid_agg_df['weekly_cases'] = group_covid_agg_df.groupby('fips')['cases'].diff()
group_covid_agg_df['weekly_cases'] = group_covid_agg_df['weekly_cases'].fillna(group_covid_agg_df['cases'])

In [62]:
group_covid_agg_df

                 cases  deaths     county state stay_at_home_announced  \
fips  YEAR WEEK
01001 2020 13        6     0.0    Autauga    AL                     no
           14       12     0.0    Autauga    AL                     no
           15       19     1.0    Autauga    AL                    yes
           16       27     2.0    Autauga    AL                    yes
           17       37     2.0    Autauga    AL                    yes
...                ...     ...        ...   ...                    ...
VI    2020 45      803    15.0  St. Croix  None                     no
           46      812    15.0  St. Croix  None                     no
           47      849    15.0  St. Croix  None                     no
           48      869    15.0  St. Croix  None                     no
           49      898    15.0  St. Croix  None                     no

                stay_at_home_effective  total_population  \
fips  YEAR WEEK
01001 2020 13                       no           55049.0
           14                       no           55049.0
           15                      yes           55049.0
           16                      yes           55049.0
           17                      yes           55049.0
...                                ...               ...
VI    2020 45                       no               NaN
           46                       no               NaN
           47                       no               NaN
           48                       no               NaN
           49                       no               NaN

                 population_density_per_sqmi date_stay_at_home_announced  \
fips  YEAR WEEK
01001 2020 13                      92.605533                  2020-04-03
           14                      92.605533                  2020-04-03
           15                      92.605533                  2020-04-03
           16                      92.605533                  2020-04-03
           17                      92.605533                  2020-04-03
...                                      ...                         ...
VI    2020 45                            NaN                        None
           46                            NaN                        None
           47                            NaN                        None
           48                            NaN                        None
           49                            NaN                        None

                date_stay_at_home_effective  ...  percent_below_poverty  fog  \
fips  YEAR WEEK                              ...
01001 2020 13                    2020-04-04  ...                   12.3  0.0
           14                    2020-04-04  ...                   12.3  0.0
           15                    2020-04-04  ...                   12.3  2.0
           16                    2020-04-04  ...                   12.3  0.0
           17                    2020-04-04  ...                   12.3  2.0
...                                     ...  ...                    ...  ...
VI    2020 45                          None  ...                    NaN  0.0
           46                          None  ...                    NaN  0.0
           47                          None  ...                    NaN  0.0
           48                          None  ...                    NaN  0.0
           49                          None  ...                    NaN  0.0

                 rain  snow  thunder  visibility  max_wind_speed        lat  \
fips  YEAR WEEK
01001 2020 13     1.0   0.0      0.0    9.633333       10.333333  32.534928
           14     2.0   0.0      1.0    9.971429        8.328571  32.534928
           15     5.0   0.0      2.0    9.128571       11.842857  32.534928
           16     3.0   0.0      2.0    9.785714       13.414286  32.534928
           17     3.0   0.0      2.0    9.200000       12.128571  32.534928
...               ...   ...      ...         ...             ...        ...
VI    2020 45     0.0   0.0      0.0         NaN             NaN        NaN
           46     0.0   0.0      0.0         NaN             NaN        NaN
           47     0.0   0.0      0.0         NaN             NaN        NaN
           48     0.0   0.0      0.0         NaN             NaN        NaN
           49     0.0   0.0      0.0         NaN             NaN        NaN

                       lon  weekly_cases
fips  YEAR WEEK
01001 2020 13   -86.642748           6.0
           14   -86.642748           6.0
           15   -86.642748           7.0
           16   -86.642748           8.0
           17   -86.642748          10.0
...                    ...           ...
VI    2020 45          NaN           7.0
           46          NaN           9.0
           47          NaN          37.0
           48          NaN          20.0
           49          NaN          29.0

[112693 rows x 21 columns]

In [63]:
# filter out invalid fips code
group_covid_agg_df.reset_index(inplace=True)
group_covid_agg_df = group_covid_agg_df[group_covid_agg_df['fips'].astype(str).str.len() == 5]

In [64]:
# find the state code and county code
group_covid_agg_df['STATEFP'] = group_covid_agg_df['fips'].astype(str).str[:2]
group_covid_agg_df['COUNTYFP'] = group_covid_agg_df['fips'].astype(str).str[2:5]

C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\3644125361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  group_covid_agg_df['STATEFP'] = group_covid_agg_df['fips'].astype(str).str[:2]
C:\Users\bianh\AppData\Local\Temp\ipykernel_33124\3644125361.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  group_covid_agg_df['COUNTYFP'] = group_covid_agg_df['fips'].astype(str).str[2:5]

In [65]:
group_covid_agg_df

,fips,YEAR,WEEK,cases,deaths,county,state,stay_at_home_announced,stay_at_home_effective,total_population,...,rain,snow,thunder,visibility,max_wind_speed,lat,lon,weekly_cases,STATEFP,COUNTYFP
0,01001,2020,13,6,0.0,Autauga,AL,no,no,55049.0,...,1.0,0.0,0.0,9.633333,10.333333,32.534928,-86.642748,6.0,01,001
1,01001,2020,14,12,0.0,Autauga,AL,no,no,55049.0,...,2.0,0.0,1.0,9.971429,8.328571,32.534928,-86.642748,6.0,01,001
2,01001,2020,15,19,1.0,Autauga,AL,yes,yes,55049.0,...,5.0,0.0,2.0,9.128571,11.842857,32.534928,-86.642748,7.0,01,001
3,01001,2020,16,27,2.0,Autauga,AL,yes,yes,55049.0,...,3.0,0.0,2.0,9.785714,13.414286,32.534928,-86.642748,8.0,01,001
4,01001,2020,17,37,2.0,Autauga,AL,yes,yes,55049.0,...,3.0,0.0,2.0,9.200000,12.128571,32.534928,-86.642748,10.0,01,001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112522,56045,2020,45,306,0.0,Weston,WY,no,no,7175.0,...,0.0,0.0,0.0,NaN,NaN,43.840417,-104.567663,142.0,56,045
112523,56045,2020,46,339,0.0,Weston,WY,no,no,7175.0,...,0.0,0.0,0.0,NaN,NaN,43.840417,-104.567663,33.0,56,045
112524,56045,2020,47,372,0.0,Weston,WY,no,no,7175.0,...,0.0,0.0,0.0,NaN,NaN,43.840417,-104.567663,33.0,56,045
112525,56045,2020,48,396,1.0,Weston,WY,no,no,7175.0,...,0.0,0.0,0.0,NaN,NaN,43.840417,-104.567663,24.0,56,045
112526,56045,2020,49,419,2.0,Weston,WY,no,no,7175.0,...,0.0,0.0,0.0,NaN,NaN,43.840417,-104.567663,23.0,56,045

In [66]:
group_covid_agg_df.to_csv('./dataset/covid_county_week.csv', index = False)

In [67]:
airline_df = pd.read_csv('./dataset/geo_airports_week.csv')
airline_df.rename(columns={'COUNTY' :'county', 'STATE' : 'state'}, inplace=True)

In [68]:
airline_df

,ORIGIN_AIRPORT_ID,YEAR,WEEK,CANCELLED,COUNT_FLIGHTS,WEATHER_CANCELLED,NAS_CANCELLED,SEC_CANCELLED,CARRIER_CANCELLED,Description,IATA,AIRPORT,CITY,state,COUNTRY,LATITUDE,LONGITUDE
0,10140,2018,1,1,362,1,0,0,0,"Albuquerque, NM: Albuquerque International Sun...",ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
1,10140,2018,2,1,269,1,0,0,0,"Albuquerque, NM: Albuquerque International Sun...",ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
2,10140,2018,3,5,270,3,0,0,2,"Albuquerque, NM: Albuquerque International Sun...",ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
3,10140,2018,4,0,270,0,0,0,0,"Albuquerque, NM: Albuquerque International Sun...",ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
4,10140,2018,5,0,266,0,0,0,0,"Albuquerque, NM: Albuquerque International Sun...",ABQ,Albuquerque International,Albuquerque,NM,USA,35.040222,-106.609194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21177,15624,2022,27,2,216,0,0,0,2,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",VPS,Eglin Air Force Base,Valparaiso,FL,USA,30.483250,-86.525400
21178,15624,2022,28,5,210,1,0,0,4,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",VPS,Eglin Air Force Base,Valparaiso,FL,USA,30.483250,-86.525400
21179,15624,2022,29,5,209,2,0,0,3,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",VPS,Eglin Air Force Base,Valparaiso,FL,USA,30.483250,-86.525400
21180,15624,2022,30,3,206,1,0,1,1,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",VPS,Eglin Air Force Base,Valparaiso,FL,USA,30.483250,-86.525400
21181,15624,2022,52,2,22,1,0,0,1,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",VPS,Eglin Air Force Base,Valparaiso,FL,USA,30.483250,-86.525400

In [69]:
# covid_airline_df = group_covid_agg_df.'county','state'merge(airline_df, on=[, 'YEAR', 'week'])